---
- name: Install Rundeck
  hosts: all 
  become: yes

  tasks:
  - name: apt update
    apt:
     name: "*"
     state: latest
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes

  - name: Install openjdk-8-jdk-headless
    apt:
     name: openjdk-8-jdk-headless
     state: latest
 
  - name: Download and Install package
    apt:
     deb: https://dl.bintray.com/rundeck/rundeck-deb/rundeck_3.3.6.20201111-1_all.deb
  - name: Run Service Rundeck
    service:
     name: rundeckd
     state: started
